language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9a3656e6a885_key -iv $encrypted_9a3656e6a885_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
