language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_985c4f58c611_key -iv $encrypted_985c4f58c611_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
