language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d43ce5b91fd8_key -iv $encrypted_d43ce5b91fd8_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
